name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Install pytest
        run: |
          pip install pytest
      
      - name: List directory contents
        run: ls -l /home/runner/work/site_3d/site_3d  # Проверяем файлы в каталоге

      - name: Check current working directory from Python
        run: |
          python -c "import os; print(os.getcwd())"  # Проверяем рабочий каталог Python

      - name: Print sys.path from Python
        run: |
          python -c "import sys; print(sys.path)"  # Проверяем пути поиска Python

      - name: Set PYTHONPATH
        run: |
          export PYTHONPATH=$(pwd):$PYTHONPATH  # Добавляем корень проекта в PYTHONPATH
        
      - name: Run tests
        run: |
          pytest
